[DEFAULT]
core_plugin = ml2
transport_url = rabbit://openstack:RABBIT_PASS@controller

[agent]
root_helper = "sudo /usr/bin/neutron-rootwrap /etc/neutron/rootwrap.conf"


[oslo_concurrency]
lock_path = /var/lib/neutron/tmp

